### ISSUE TITLE
推理报错

### ISSUE THREAD

**Issue by dongguanting** [zjukg/KnowPAT#10]
训练后加载模型推理时报错，请问这是什么原因

Traceback (most recent call last):
  File "/cpfs01/shared/KnowPAT/inference.py", line 68, in <module>
    model = LlamaForCausalLM.from_pretrained(
  File "/opt/conda/envs/llama_factory/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3787, in from_pretrained
    model.load_adapter(
  File "/opt/conda/envs/llama_factory/lib/python3.10/site-packages/transformers/integrations/peft.py", line 193, in load_adapter
    adapter_state_dict = load_peft_weights(peft_model_id, token=token, **adapter_kwargs)
  File "/opt/conda/envs/llama_factory/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 244, in load_peft_weights
    has_remote_safetensors_file = file_exists(
  File "/opt/conda/envs/llama_factory/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/envs/llama_factory/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/KnowPAT/checkpoint/nq_5k/checkpoint-1800/'. Use `repo_type` argument if needed.

加载的checkpoint如下：
![image](https://github.com/zjukg/KnowPAT/assets/60767110/dc2a256b-ea5d-4649-8a8b-d34a478552f9)

**Comment by ghost** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，现在无法亲自回复您的邮件。我会尽快给您回复。

**Comment by Zhang-Each** [comment]
inference部分的代码默认加载的是训练完成后的模型文件中的adapter_model.bin，如果要加载checkpoint，可以尝试把pytorch_model.bin改名为adapter_model.bin

**Comment by dongguanting** [comment]
请问inference.py中，save path和model path分别填入什么呢？

我猜测：
save path填入checkpoint文件夹的path
model path直接填入原始llama的path吗？

**Comment by Zhang-Each** [comment]
你好，是的
